# name: GitHub Pages

# on:
#   push:
#     branches:
#     - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2

#     - name: Setup Node.js
#       uses: actions/setup-node@v2
#       with:
#         node-version: '16'

#     - name: Install dependencies
#       run: npm install

#     - name: Run tests
#       run: npm run test:headless

#     - name: Build
#       run: npm run build:prod

#     - name: Deploy
#       if: success()
#       uses: peaceiris/actions-gh-pages@v3
#       with:
#         deploy_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
#         publish_dir: dist/testcode
#         enable_jekyll: true
name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
        aws-region: eu-central-1

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test:headless
      
    - name: GitHub Script
      uses: actions/github-script@v2.1.0
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/${{ github.event.head_commit.message }}',
            sha: context.sha
          })

    - name: Build
      run: npm run build:prod

    - name: Deploy
      if: success()
      run: aws s3 sync ./dist/testcode s3://thanostestcicd